const supabaseUrl = 'https://nyjnhphuwlhwjconeudl.supabase.co';
const supabaseKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55am5ocGh1d2xod2pjb25ldWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ0MDMyODgsImV4cCI6MjAyOTk3OTI4OH0.mWDiQS6fvroXjAiACfrFsXjtVsfAVDZVKv8bQMOScGg';
